alias: Défi Hilo Préchauffe AM
description: "Gère la préchauffe Hilo du matin/Manages the AM pre-heat phase of a Hilo Challenge"
mode: single
triggers:
  - entity_id:
      - sensor.defi_hilo
    to: pre_heat
    enabled: true
    from: appreciation
    trigger: state
  - at: "04:00:00"
    trigger: time
conditions:
  - condition: time
    before: "04:05:00"
    after: "03:55:00"
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.defi_hilo
        state: pre_heat
      - condition: state
        entity_id: sensor.defi_hilo
        state: reduction
actions:
  - data:
      temperature: 15
    target:
      entity_id: climate.thermostat_salle_de_bain
    action: climate.set_temperature
  - metadata: {}
    data: {}
    target:
      entity_id: switch.prise_echangeur_d_air
    action: switch.turn_off
