alias: Défi Hilo Ancrage AM
description: "Permet de gérer la période d'ancrage AM d'un défi Hilo/Manages the AM anchor phase of a Hilo Challenge"
mode: single
triggers:
  - at: "01:00:00"
    trigger: time
  - entity_id:
      - sensor.defi_hilo
    to: appreciation
    trigger: state
conditions:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{'am' in state_attr('sensor.defi_hilo','next_events')[0]['period'] }}"
      - condition: template
        value_template: >-
          {{ (state_attr('sensor.defi_hilo',
          'next_events')[0]['phases']['preheat_start'] |
          as_datetime).strftime('%Y-%m-%d') == now().strftime('%Y-%m-%d') }}
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.defi_hilo
        state: appreciation
      - condition: state
        entity_id: sensor.defi_hilo
        state: scheduled
  - condition: time
    after: "00:55:00"
    before: "01:05:00"
actions:
  - action: climate.set_temperature
    metadata: {}
    data: {}
    target:
      entity_id: climate.thermostat_cuisine
