alias: Défi Hilo Recovery AM
description: "Permet de gérer la période de reprise AM/Manages the AM recovery phase of a Hilo Challenge"
mode: single
triggers:
  - entity_id:
      - sensor.defi_hilo
    to: recovery
    from: reduction
    trigger: state
  - at: "10:00:00"
    trigger: time
conditions:
  - condition: time
    before: "10:05:00"
    after: "09:55:00"
actions:
  - data:
      temperature: 18
    target:
      entity_id:
        - climate.thermostat_cuisine
    action: climate.set_temperature
  - metadata: {}
    data: {}
    target:
      entity_id: switch.prise_echangeur_d_air
    action: switch.turn_on
